import {GetStaticProps} from 'next';
import Head from 'next/head';
import {CHAINS, ChainPropT, MarkdownForChainIdT} from 'types';
import {fetchMarkdownForChainId} from 'utils/markdown';
import Protocol from './core';

type IndexProps = {
  chain: ChainPropT;
  markdown: MarkdownForChainIdT;
};

export default function Index({chain, markdown}: IndexProps) {
  return (
    <>
      <Head>
        <title>Core Learn Web3 Stack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Protocol chain={chain} markdown={markdown} />
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const chainId = CHAINS.CORE;
  const markdown = fetchMarkdownForChainId(chainId);

  const chain: ChainPropT = {
    id: chainId,
    label: 'Core', // Provide a label or adjust as needed
    active: false,
    logoUrl: '',
    steps: [],
    protocol: '/path/to/protocol/RPC', // Adjust as necessary
    network: '/path/to/network/TESTNET', // Adjust as necessary
  };

  return {
    props: {
      chain,
      markdown,
    },
  };
};
